In [2]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [7]:
%time
for _ in range(10):
    my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 7.39 μs


In [8]:
%time
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

CPU times: total: 0 ns
Wall time: 6.91 μs


In [9]:
# In [5]:  %time for _ in range(10): my_arr2 = my_arr * 2
# CPU times: total: 15.6 ms
# Wall time: 27.7 ms

# In [6]:  %time for _ in range(10): my_list2 = [x * 2 for x in my_list]
# CPU times: total: 703 ms
# Wall time: 692 ms

# NumPy-based algorithms are generally 10 to 100 times faster (or more)
#  than their pure Python counterparts and use significantly less memory

In [ ]:
# Generates a 2 × 3 array of random numbers
data = np.random.randn(2, 3) 

In [11]:
data

array([[-0.70184946, -1.63122689,  0.04127737],
       [ 0.575361  ,  0.34014464,  0.53688185]])

In [12]:
data * 10

array([[ -7.0184946 , -16.31226886,   0.41277366],
       [  5.75361004,   3.40144635,   5.36881845]])

In [13]:
data + data

array([[-1.40369892, -3.26245377,  0.08255473],
       [ 1.15072201,  0.68028927,  1.07376369]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [1]:
data1 = [6, 7.5, 8, 0, 1] 

In [5]:
arr1 = np.array(data1)

In [ ]:
arr1 # NumPy array

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 

In [9]:
arr2 = np.array(data2)

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype # The single float value affects all.

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones((3, 6)) # To create a higher dimensional
#  array with these methods, pass a tuple for the shape:

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.empty((2, 3, 2))

array([[[9.35120184e-312, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.61590357e+184]],

       [[6.19772585e-091, 1.51924665e-047],
        [5.45252122e-067, 1.86317877e+160],
        [6.48224660e+170, 4.93432906e+257]]])

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [8]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [13]:
arr = np.array([1, 2, 3, 4, 5])

In [15]:
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)

In [17]:
float_arr.dtype

dtype('float64')

In [18]:
arrr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [21]:
int_arrr = arrr.astype(np.int32)

In [22]:
int_arrr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
numeric_strings = np.array(["1.244", "-5.6", '345'], dtype=np.bytes_)

In [26]:
numeric_strings.astype(float)

array([  1.244,  -5.6  , 345.   ])

In [27]:
int_array = np.arange(10) 

In [28]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 

In [29]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Calling astype always creates a new array (a copy of the data), 
# even if the new dtype is the same as the old dtype.

int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])    # Vectorization

In [4]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) 

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [14]:
(arr2 > arr).dtype

dtype('bool')

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

First axis (blocks): one block = 4 rows × 5 cols = 20 elements (each value is 8 bytes).
Middle axis (rows): one row has 5 elements.
Last axis (columns): move 1 column → move 8 bytes.

In [2]:
ints = np.ones(10, dtype=np.uint16)

In [3]:
floats = np.ones(10, dtype=np.float32)

In [ ]:
np.issubdtype(ints.dtype, np.integer) # dtypes superclasses.

True

In [5]:
np.issubdtype(floats.dtype, np.floating)

True

In [ ]:
np.float64.mro() # Resolution order.

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [15]:
arr = np.arange(8)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [3]:
arr2 = np.arange(12)

In [4]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr2.reshape((4, 3), order="C") # Row major.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr2.reshape((4, 3), order="F") # Column major.

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [2]:
arr = np.arange(15)

In [3]:
arr.reshape((5, -1)) # -1 means Figure out this dimension automatically.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
other_arr = np.ones((3, 5))

In [5]:
other_arr.shape

(3, 5)

In [8]:
other_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Since an array’s shape attribute is a tuple, it can be passed to reshape, too
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr = np.arange(15).reshape((5, 3))

In [12]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr = np.arange(10)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[5]

np.int64(5)

In [ ]:
arr[5:8] # Create a slice of arr:

array([5, 6, 7])

In [35]:
arr[5:8] = 12 # You will need to explicitly copy the array.

In [20]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [21]:
arr_slice = arr[5:8]

In [22]:
arr_slice

array([12, 12, 12])

In [23]:
arr_slice[1] = 12345

In [25]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [26]:
arr_slice[:] = 64

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [29]:
arr2d[2]

array([7, 8, 9])

In [30]:
arr2d[0][2]

np.int64(3)

In [ ]:
arr2d[0, 2] # Accessing 2d arrays.

np.int64(3)

In [4]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [4]:
arr3d # 2 × 2 × 3 array arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0] # a 2 × 3 array.

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
old_values = arr3d[0].copy()

In [7]:
arr3d[0] = 42

In [8]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0] = old_values

In [10]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[1, 0]

array([7, 8, 9])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# (1:) Means: take columns from index 1 to the end. Apply this to each selected row.
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [26]:
# arr2d[row_index, column_slice]
arr2d[1, :2] 

array([4, 5])

In [5]:
arr2d[:2, 2]

array([3, 6])

In [ ]:
arr2d[:, 0]

array([1, 4, 7])

In [11]:
arr2d[:, :1] # A slice, therefore, selects a range of elements along an axis.

array([[1],
       [4],
       [7]])

In [15]:
arr2d[:2, 1:] = 0 # Assigning to a slice expression assigns to the whole selection.

In [ ]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [19]:
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
column3 = arr2D[:, 2] # Collapse row dimension.
column3.shape 

(3,)

In [24]:
column3 = arr2D[:, 2:] # Preserve row dimension.
column3.shape 

(3, 1)

Boolean Indexing

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
data = np.random.randn(7, 4)

In [4]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [5]:
data

array([[-2.21197896, -0.48698655, -1.31104277, -0.0091113 ],
       [-0.57895941,  1.06300386, -0.15401915, -0.8151132 ],
       [ 0.01901495,  0.02921448,  0.36783882,  0.38357804],
       [-0.69029492,  0.10837744, -0.68022781, -1.00894824],
       [ 0.06166988,  0.83322625,  0.68005832, -0.75699127],
       [ 0.14313303,  2.29932793,  0.04399819,  1.55924555],
       [-0.08344502,  0.98074101, -0.25135635,  2.19634377]])

In [7]:
# Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. 
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [9]:
# The boolean array must be of the same length as the array axis it’s indexing.
data[names == "Bob"]

array([[-2.21197896, -0.48698655, -1.31104277, -0.0091113 ],
       [-0.69029492,  0.10837744, -0.68022781, -1.00894824]])

In [10]:
data[names == "Bob", 2:]

array([[-1.31104277, -0.0091113 ],
       [-0.68022781, -1.00894824]])

In [13]:
# Only 1 column is selected, so both entries are put in the same list.
data[names == "Bob", 3]

array([-0.0091113 , -1.00894824])

In [14]:
data[names == "Bob", 3:]

array([[-0.0091113 ],
       [-1.00894824]])

In [15]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [16]:
data[~(names == "Bob")]

array([[-0.57895941,  1.06300386, -0.15401915, -0.8151132 ],
       [ 0.01901495,  0.02921448,  0.36783882,  0.38357804],
       [ 0.06166988,  0.83322625,  0.68005832, -0.75699127],
       [ 0.14313303,  2.29932793,  0.04399819,  1.55924555],
       [-0.08344502,  0.98074101, -0.25135635,  2.19634377]])

In [17]:
# Invert a general condition.
cond = names == "Bob"

In [18]:
data[~cond]

array([[-0.57895941,  1.06300386, -0.15401915, -0.8151132 ],
       [ 0.01901495,  0.02921448,  0.36783882,  0.38357804],
       [ 0.06166988,  0.83322625,  0.68005832, -0.75699127],
       [ 0.14313303,  2.29932793,  0.04399819,  1.55924555],
       [-0.08344502,  0.98074101, -0.25135635,  2.19634377]])

In [19]:
# To combine multiple boolean conditions, use & or |

mask = (names == "Bob") | (names == "Will")

In [21]:
mask

array([ True, False,  True,  True,  True, False, False])

In [24]:
data[mask]

array([[-2.21197896, -0.48698655, -1.31104277, -0.0091113 ],
       [ 0.01901495,  0.02921448,  0.36783882,  0.38357804],
       [-0.69029492,  0.10837744, -0.68022781, -1.00894824],
       [ 0.06166988,  0.83322625,  0.68005832, -0.75699127]])

Selecting data from an array by boolean indexing always creates a copy of
the data, even if the returned array is unchanged.

In [28]:
# To set all of the negative values in data to 0:
data[data < 0] = 0

In [29]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.06300386, 0.        , 0.        ],
       [0.01901495, 0.02921448, 0.36783882, 0.38357804],
       [0.        , 0.10837744, 0.        , 0.        ],
       [0.06166988, 0.83322625, 0.68005832, 0.        ],
       [0.14313303, 2.29932793, 0.04399819, 1.55924555],
       [0.        , 0.98074101, 0.        , 2.19634377]])

In [33]:
data[names != "Joe"] = 7

data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.06300386, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.14313303, 2.29932793, 0.04399819, 1.55924555],
       [0.        , 0.98074101, 0.        , 2.19634377]])

Fancy Indexing: Indexing using integer arrays.

In [34]:
arr = np.empty((8, 4))

In [39]:
for i in range(8):
    arr[i] = i

In [40]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [41]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [42]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [48]:
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
# Always selects a 1D array of elements corresponding to each tuple of indices.
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [54]:
# Do it piece by piece to understand well.
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Transposing Arrays and Swapping Axes

In [55]:
arr = np.arange(15).reshape((3, 5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [3]:
arr = np.random.randn(6, 3)

arr # (6 x 3)

array([[ 2.79423603e-01,  2.29022905e+00, -1.49967194e-01],
       [ 1.48975433e+00,  1.94010568e+00, -1.77988782e-01],
       [ 6.99702178e-01, -1.16886731e-02,  2.50747989e-01],
       [-5.30441677e-01, -4.71855098e-04,  8.88082715e-01],
       [ 2.72406142e-01,  6.30427624e-02,  1.05998670e-01],
       [ 1.28382407e+00, -1.79890450e-01, -5.82329781e-01]])

In [4]:
arr.T # (3 x 6)

array([[ 2.79423603e-01,  1.48975433e+00,  6.99702178e-01,
        -5.30441677e-01,  2.72406142e-01,  1.28382407e+00],
       [ 2.29022905e+00,  1.94010568e+00, -1.16886731e-02,
        -4.71855098e-04,  6.30427624e-02, -1.79890450e-01],
       [-1.49967194e-01, -1.77988782e-01,  2.50747989e-01,
         8.88082715e-01,  1.05998670e-01, -5.82329781e-01]])

In [5]:
# Computing the inner matrix product: (Am×n​) ⋅ (Bn×p​)
# The inside dimensions must match; result shape becomes: (m×p)

np.dot(arr.T, arr) 

array([[ 4.79080639,  3.30852214, -1.32142541],
       [ 3.30852214,  9.04563095, -0.58068821],
       [-1.32142541, -0.58068821,  1.25607932]])

For higher dimensional arrays, transpose will accept a tuple of axis
numbers to permute the axes.

In [6]:
arr = np.arange(16).reshape((2, 2, 4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

Page 0:
row 0 -> [0 1 2 3]
row 1 -> [4 5 6 7]

Page 1:
row 0 -> [ 8  9 10 11]
row 1 -> [12 13 14 15]

Swap axis 0 and axis 1 --> Take axis 1 first, axis 0 second, axis 2 third (stays unchanged).

In simpler terms: Rows become pages, and pages become rows.

New Page 0: Take all the old row 0s.

New Page 1: Take all the old row 1s.

In [7]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

A universal function, or ufunc, is a function that performs element-wise
operations on data in ndarrays.

In [3]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Unary ufuncs
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
# Take the exponential e^x
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
# Binary ufuncs

x = np.random.randn(8)

y = np.random.randn(8)

In [11]:
x

array([ 0.53982921, -0.36924582, -1.09353769,  1.47617129,  0.14891686,
       -0.66664721, -1.41255443,  0.26651439])

In [12]:
y

array([ 0.45650614, -1.92805795,  0.44795624, -0.01347065, -0.87332296,
       -0.60925676, -1.15377275,  1.81340185])

In [13]:
np.maximum(x, y)

array([ 0.53982921, -0.36924582,  0.44795624,  1.47617129,  0.14891686,
       -0.60925676, -1.15377275,  1.81340185])

While not common, a ufunc can return multiple arrays.

In [3]:
arr = np.random.randn(7) * 5

arr

array([-0.64562033, -7.4905965 ,  0.0528699 , -0.09045622,  6.79776075,
       -1.50849572,  1.15572968])

In [4]:
remainder, whole_part = np.modf(arr)

In [5]:
remainder

array([-0.64562033, -0.4905965 ,  0.0528699 , -0.09045622,  0.79776075,
       -0.50849572,  0.15572968])

In [6]:
whole_part

array([-0., -7.,  0., -0.,  6., -1.,  1.])

Ufuncs accept an optional out argument that allows them to operate in
place on arrays:

In [7]:
arr

array([-0.64562033, -7.4905965 ,  0.0528699 , -0.09045622,  6.79776075,
       -1.50849572,  1.15572968])

In [8]:
np.sqrt(arr)

C:\Users\pc\AppData\Local\Temp\ipykernel_13028\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 0.22993456,        nan, 2.60725157,
              nan, 1.07504869])

In [10]:
# The second arr is the out argument. --> “Store the result back inside arr itself.”
np.sqrt(arr, arr)

array([       nan,        nan, 0.47951492,        nan, 1.6146986 ,
              nan, 1.03684555])

In [11]:
arr

array([       nan,        nan, 0.47951492,        nan, 1.6146986 ,
              nan, 1.03684555])