In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [7]:
%time
for _ in range(10):
    my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 7.39 μs


In [8]:
%time
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

CPU times: total: 0 ns
Wall time: 6.91 μs


In [9]:
# In [5]:  %time for _ in range(10): my_arr2 = my_arr * 2
# CPU times: total: 15.6 ms
# Wall time: 27.7 ms

# In [6]:  %time for _ in range(10): my_list2 = [x * 2 for x in my_list]
# CPU times: total: 703 ms
# Wall time: 692 ms

# NumPy-based algorithms are generally 10 to 100 times faster (or more)
#  than their pure Python counterparts and use significantly less memory

In [ ]:
# Generates a 2 × 3 array of random numbers
data = np.random.randn(2, 3) 

In [11]:
data

array([[-0.70184946, -1.63122689,  0.04127737],
       [ 0.575361  ,  0.34014464,  0.53688185]])

In [12]:
data * 10

array([[ -7.0184946 , -16.31226886,   0.41277366],
       [  5.75361004,   3.40144635,   5.36881845]])

In [13]:
data + data

array([[-1.40369892, -3.26245377,  0.08255473],
       [ 1.15072201,  0.68028927,  1.07376369]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [1]:
data1 = [6, 7.5, 8, 0, 1] 

In [5]:
arr1 = np.array(data1)

In [ ]:
arr1 # NumPy array

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 

In [9]:
arr2 = np.array(data2)

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype # The single float value affects all.

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones((3, 6)) # To create a higher dimensional
#  array with these methods, pass a tuple for the shape:

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.empty((2, 3, 2))

array([[[9.35120184e-312, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.61590357e+184]],

       [[6.19772585e-091, 1.51924665e-047],
        [5.45252122e-067, 1.86317877e+160],
        [6.48224660e+170, 4.93432906e+257]]])

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])