In [2]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [7]:
%time
for _ in range(10):
    my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 7.39 μs


In [8]:
%time
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

CPU times: total: 0 ns
Wall time: 6.91 μs


In [9]:
# In [5]:  %time for _ in range(10): my_arr2 = my_arr * 2
# CPU times: total: 15.6 ms
# Wall time: 27.7 ms

# In [6]:  %time for _ in range(10): my_list2 = [x * 2 for x in my_list]
# CPU times: total: 703 ms
# Wall time: 692 ms

# NumPy-based algorithms are generally 10 to 100 times faster (or more)
#  than their pure Python counterparts and use significantly less memory

In [ ]:
# Generates a 2 × 3 array of random numbers
data = np.random.randn(2, 3) 

In [11]:
data

array([[-0.70184946, -1.63122689,  0.04127737],
       [ 0.575361  ,  0.34014464,  0.53688185]])

In [12]:
data * 10

array([[ -7.0184946 , -16.31226886,   0.41277366],
       [  5.75361004,   3.40144635,   5.36881845]])

In [13]:
data + data

array([[-1.40369892, -3.26245377,  0.08255473],
       [ 1.15072201,  0.68028927,  1.07376369]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [1]:
data1 = [6, 7.5, 8, 0, 1] 

In [5]:
arr1 = np.array(data1)

In [ ]:
arr1 # NumPy array

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 

In [9]:
arr2 = np.array(data2)

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [ ]:
arr1.dtype # The single float value affects all.

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones((3, 6)) # To create a higher dimensional
#  array with these methods, pass a tuple for the shape:

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.empty((2, 3, 2))

array([[[9.35120184e-312, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.61590357e+184]],

       [[6.19772585e-091, 1.51924665e-047],
        [5.45252122e-067, 1.86317877e+160],
        [6.48224660e+170, 4.93432906e+257]]])

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [8]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [13]:
arr = np.array([1, 2, 3, 4, 5])

In [15]:
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)

In [17]:
float_arr.dtype

dtype('float64')

In [18]:
arrr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [21]:
int_arrr = arrr.astype(np.int32)

In [22]:
int_arrr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
numeric_strings = np.array(["1.244", "-5.6", '345'], dtype=np.bytes_)

In [26]:
numeric_strings.astype(float)

array([  1.244,  -5.6  , 345.   ])

In [27]:
int_array = np.arange(10) 

In [28]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 

In [29]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Calling astype always creates a new array (a copy of the data), 
# even if the new dtype is the same as the old dtype.

int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])    # Vectorization

In [4]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) 

In [10]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [14]:
(arr2 > arr).dtype

dtype('bool')